### PR TITLE
Mappings for paper versions of schedules A and B

### PR DESCRIPTION
**Pull request by esonderegger**
This PR is what I hope will be the first of many, bringing in the mappings for paper versions of the .fec file format. Most of these were done by @chriszs when he was working on [fec-parse](https://github.com/PublicI/fec-parse) but then I added additional ones when working on [fecfile](https://github.com/esonderegger/fecfile).

We've both been working from a mappings file where for each form, each revision of the form is a key with its values being an array of the `canonical` fields. This has turned out to be pretty well-suited for hand-editing but ends up being quite verbose. One of the challenges was writing a script that converted from this `mappings.json` file back to csv. My hope is that the new csvs change as little as possible about the original. Ideally, this would mean only adding new rows to the bottom and new columns to the right.

Two questions spring to mind when thinking about how best to do these:

- What are the columns with the full name for the mapping for that version used for? In other words, columns 3,5,7... Is it important to leave a column after each new version, possibly to be filled in at a later date?
- Is it ok to change the regular expressions in the existing column headers? For example, in this PR, the mappings for version 3 also work for version 2, so `^3` is changed to `^3|^2`. 

My biggest fear with this PR is that comparing the diffs between the before and after will be a difficult task. This is bad for at least two reasons:

- I already feel sorry for asking you to read this much.
- The harder it is to review, the easier it is to miss something that ends up being a breaking change.

Is there anything I can do to help make the reviewing task easier for this? I tried running the changes through [csv-diff](https://github.com/simonw/csv-diff) and unfortunately I couldn't get it to do what I wanted it do.

Thank you so much for taking a look at this!

### CODE REVIEW

**Comment by dwillis** [comment]
@esonderegger thanks for this! to answer your questions:

1. Those columns contain the name from the form just as a reference. I've found them helpful.
2. It is fine to change the regular expressions to accommodate multiple versions, absolutely.

I'll take a look at this, probably next week.

**Comment by dwillis** [comment]
@esonderegger This looks good to me, but I would appreciate another set of eyes on testing it out.

**Comment by esonderegger** [comment]
Thanks for taking a look at this and merging it! I’m on my honeymoon right now and won’t be back in front of a real computer until May 27. I’ll be happy to do another check and see if I can tweak the script to grab the names from the forms as well when I’m back. Thanks again!

**Comment by chriszs** [comment]
@esonderegger is the script you used to convert from the JSON available somewhere?

**Pull request merged**
